# Generated by Django 5.0.1 on 2024-01-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0002_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('CHS', 'Горячие и холодные закуски'), ('SLD', 'Салаты'), ('SPS', 'Супы'), ('SDS', 'Гарниры'), ('HOT', 'Горячее'), ('SUS', 'Соусы'), ('DST', 'Десерты'), ('AHL', 'Алкоголь')], default='BRK', max_length=3, verbose_name='Тип'),
        ),
    ]
